### ISSUE TITLE
Row names warning message

### ISSUE THREAD

**Issue by sickler-alex** [GeneDx/scramble#1]
When running SCRAMBLE-MEI on the example data, I'm getting the following warnings:

Sample had 1 MEI(s)
Warning messages:
1: In data.frame(df.all, alignments_fwd, stringsAsFactors = F) :
  row names were found from a short variable and have been discarded
2: In data.frame(df.all, alignments_rev, stringsAsFactors = F) :
  row names were found from a short variable and have been discarded
Done analyzing MEIs
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

**Comment by CarlosBorroto** [comment]
Fixed in https://github.com/GeneDx/scramble/commit/cf92d7b709da044f9afcbb5a32f29dfd85d632f3
