### ISSUE TITLE
negative length vectors are not allowed

### ISSUE THREAD

**Issue by exeter-matthew-wakeling** [GeneDx/scramble#2]
Hi.

I'm trying to run scramble on some WGS data. Some of the samples have processed through correctly, but some give the following error while running the analyse step:

```
Error in .Call2("PairwiseAlignmentsSingleSubject_align_aligned", x, gapCode,  : 
  negative length vectors are not allowed
Calls: do.meis ... as.matrix -> aligned -> aligned -> .local -> .Call2
Execution halted
```

Please let me know if you need any further information. I will now try and see if I can isolate the row in the cluster file that causes this error.

**Comment by exeter-matthew-wakeling** [comment]
Interestingly, if I split the cluster file into several chunks, and process each one separately, the error does not occur.

Is scramble running out of resources with too long a list of clusters? Is there perhaps a memory leak?

**Comment by rebecca810** [comment]
Thanks for bringing this to our attention. Could you please try this branch and see if it fixes your problem:

https://github.com/GeneDx/scramble/tree/Issue-Fix-negative-length-vectors-are-not-allowed

**Comment by rebecca810** [comment]
the fix is merged into master now, pls pull and let me know if you have any more issues, thanks!
