### ISSUE TITLE
Is it okay if I make a bioconda package for scramble?

### ISSUE THREAD

**Issue by roryk** [GeneDx/scramble#6]
Hi everyone,

Hope you are well-- would you all be up for me making a bioconda package for scramble?  

We are adding support for MEI calling in bcbio (https://github.com/bcbio/bcbio-nextgen) using scramble-- we were originally going to use MELT, but the license is one of the most insane licenses I've ever seen for software, and made it so we couldn't use it at all in bcbio.

On the topic of licenses, we were also wondering if you would consider a change in the license-- right now it's non-commercial only, but a lot of companies use bcbio and it would be awesome to extend MEI calling for them. Titus had a nice blog post a while back about the benefits of having a freer license for academics: http://ivory.idyll.org/blog/2015-on-licensing-in-bioinformatics.html and managed to change Lior's mind about it here: https://liorpachter.wordpress.com/2017/08/03/i-was-wrong-part-2/ in case that might sway your feelings. As a huge open source contributor I understand wanting to get compensated somehow for lots of hard, thankless work in the ditches, I totally get it. I think most of the time though, the benefits of having a tool get more widely adopted weighs whatever amount of money you could squeeze out of companies.

Anyway, no worries if the license switch is a no, we can work around it as we support some other non-free software as well. 

Thanks so much. Please let me know if I can help you all with anything.

**Comment by rebecca810** [comment]
Yes, it is okay to make a bioconda package for scramble (and would be much appreciated), but I'm afraid we can't budge on the license. We're also in the process of updating scramble to have clipped read deletion calling and to output VCFs, so if you wait a few weeks, those features should be available.

**Comment by roryk** [comment]
Hi Rebecca,

Great! I'll get on making the package. No worries about budging on the license, just thought I'd ask.

**Comment by hackdna** [comment]
Hi Rebecca, Bioconda does not allow downloading the source code directly from a VCS for building packages (https://bioconda.github.io/contributor/linting.html#policy). Would you mind creating a release?

**Comment by roryk** [comment]
Thanks +1 to what Ilya said-- we can make the package but we need a release version to make it against. It is nice because once we do it that way, bioconda will pick up all subsequent releases you all make automatically so you'll always have an up to date version in bioconda.

**Comment by CarlosBorroto** [comment]
Hi @hackdna and @roryk, thanks so much for the interest and the help getting scramble into bioconda. We will make a release and let you know.

**Comment by hackdna** [comment]
Hi, I was wondering if you have a timeline for making a release. The package recipe is almost finished (https://github.com/bcbio/bioconda-recipes/tree/scramble-recipe/recipes/scramble) and we are ready to submit it to Bioconda as soon as a GitHub release of Scramble is published. It doesn't have to be polished (using the current latest commit on master is fine) since it is fairly easy to update the package when new versions come out. We are looking forward to making Scramble easier to install and use.

**Comment by mfinelli** [comment]
@hackdna @roryk here you go: https://github.com/GeneDx/scramble/releases/tag/v1.0.0

**Comment by hackdna** [comment]
@mfinelli Thanks very much! Could you create a release v1.0.1 to match the cluster_identifier version (#10)?

**Comment by mfinelli** [comment]
@hackdna sorry I missed that before. here you go: https://github.com/GeneDx/scramble/releases/tag/v1.0.1

**Comment by hackdna** [comment]
Thanks for your help. Conda package v1.0.1 has been published: https://anaconda.org/bioconda/scramble

Some badges to add to `README.md`: https://anaconda.org/bioconda/scramble/badges
